### ISSUE TITLE
[ERROR] [TimeoutError: operation timed out]

### ISSUE THREAD

**Issue by naksitrallid** [sstativa/mfc-node#13]
for the last few days i see this while it's running:

> root@vm04:~/mfc# nodejs main.js
> [2017-06-12T194813] Server listening on: 0.0.0.0:9080
> [2017-06-12T194843] [ERROR] [TimeoutError: operation timed out]
> [2017-06-12T194843] Done, will search for new models in 30 second(s).
> [2017-06-12T194943] [ERROR] [TimeoutError: operation timed out]
> [2017-06-12T194943] Done, will search for new models in 30 second(s).

i performed git pull thinking this problem was already solved - no, no changes were done since my last git clone. fresh git clone produces the same error. there was probably some change on MFC side

please see issue #14 for more information. thank you @zoopzorp

**Comment by SCG82** [comment]
I have been receiving the following error since 6/12

```
[2017-06-15T195028] [DEBUG] Start searching for new models
[2017-06-15T195058] [ERROR] TimeoutError: operation timed out
    at afterTimeout (/usr/local/mfc-node/node_modules/bluebird/js/main/timers.js:16:15)
    at Timeout.timeoutTimeout (/usr/local/mfc-node/node_modules/bluebird/js/main/timers.js:59:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-06-15T195058] Done, will search for new models in 30 second(s).
[2017-06-15T195128] [DEBUG] Start searching for new models
```

**Comment by pikami** [comment]
Same here, please fix!

`
[2017-06-18T073156] [ERROR] TimeoutError: operation timed out
    at afterTimeout (/var/www/html/mfc-node/node_modules/bluebird/js/main/timers.js:16:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/var/www/html/mfc-node/node_modules/bluebird/js/main/timers.js:59:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-06-18T073156] Done, will search for new models in 120 second(s).
`

**Comment by jocphi** [comment]
Temporary fix (that worked for me): I set my Timeout to 900 seconds => no more timeouts.

**Comment by sstativa** [comment]
I would recommend to try [v2](https://github.com/sstativa/mfc-node/tree/v2) branch, it has a different way for retrieving a list of the models (not with it's own flows, but they are small). The config file should be compatible, but I'll definitely recommend to back it up first, and don't forget to do `npm install`

**Comment by sstativa** [comment]
I merged the changes made by [pikami](https://github.com/pikami), the issue should be resolved.

**Comment by SCG82** [comment]
I still receive the TimeoutError after applying pikami's commit on 25-33% of the retrieval attempts.

**Comment by sstativa** [comment]
I extended list of existing xchat servers, should be better now.

**Comment by naksitrallid** [comment]
i pulled all the changes yet i see this while the application is running:

> [2017-06-19T140719] [ERROR] { [Error: connect ECONNREFUSED 207.229.72.142:8080]
>   code: 'ECONNREFUSED',
>   errno: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '207.229.72.142',
>   port: 8080 }
> [2017-06-19T140719] Done, will search for new models in 300 second(s).
> [2017-06-19T141221] 1137 model(s) online
> [2017-06-19T141221] Done, will search for new models in 300 second(s).
> [2017-06-19T141723] 1140 model(s) online
> [2017-06-19T141723] Done, will search for new models in 300 second(s).
> [2017-06-19T142225] 1133 model(s) online
> [2017-06-19T142225] Done, will search for new models in 300 second(s).
> [2017-06-19T142728] 1133 model(s) online
> [2017-06-19T142728] Done, will search for new models in 300 second(s).
> [2017-06-19T143230] 1148 model(s) online
> [2017-06-19T143230] Done, will search for new models in 300 second(s).
> [2017-06-19T143730] [ERROR] { [Error: connect ECONNREFUSED 207.229.72.142:8080]
>   code: 'ECONNREFUSED',
>   errno: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '207.229.72.142',
>   port: 8080 }
> [2017-06-19T143730] Done, will search for new models in 300 second(s).
> [2017-06-19T144230] [ERROR] { [Error: connect ECONNREFUSED 207.229.72.144:8080]
>   code: 'ECONNREFUSED',
>   errno: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '207.229.72.144',
>   port: 8080 }
> [2017-06-19T144230] Done, will search for new models in 300 second(s).
> [2017-06-19T144733] 1123 model(s) online
> [2017-06-19T144733] Done, will search for new models in 300 second(s).
> [2017-06-19T145235] 1132 model(s) online
> [2017-06-19T145235] Done, will search for new models in 300 second(s).
> [2017-06-19T145735] [ERROR] { [Error: connect ECONNREFUSED 207.229.72.141:8080]
>   code: 'ECONNREFUSED',
>   errno: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '207.229.72.141',
>   port: 8080 }

**Comment by pikami** [comment]
@naksitrallid I'm guessing some xchat servers from the list don't work?
